edukodas_tasks_list:
    path:     /list
    defaults: { _controller: EdukodasTasksBundle:Tasks:list }
    methods:  [GET]

edukodas_tasks_add:
    path:     /add
    defaults: { _controller: EdukodasTasksBundle:Tasks:add }
    methods:  [GET, POST]

edukodas_tasks_edit:
    path:     /edit/{id}
    defaults: { _controller: EdukodasTasksBundle:Tasks:editForm }
    methods:  [GET, POST]

edukodas_tasks_delete:
    path:     /delete/{id}
    defaults: { _controller: EdukodasTasksBundle:Tasks:delete }
    methods:  [DELETE]

edukodas_task_list:
    path:     /list/all
    defaults: { _controller: EdukodasTasksBundle:TaskList:showList }
    methods:  [GET]

edukodas_task_list_get:
    path:     /list/get/{id}
    defaults: { _controller: EdukodasTasksBundle:TaskList:getList }
    methods:  [GET]
