edukodas_tasks_list:
    path:     /
    defaults: { _controller: EdukodasTasksBundle:Tasks:list }

edukodas_tasks_add:
    path:     /add
    defaults: { _controller: EdukodasTasksBundle:Tasks:add }

edukodas_tasks_edit:
    path:     /edit/{taskId}
    defaults: { _controller: EdukodasTasksBundle:Tasks:editForm }
    options:
        expose: true

edukodas_tasks_delete:
    path:     /delete/{taskId}
    defaults: { _controller: EdukodasTasksBundle:Tasks:delete }
