edukodas_fixtures:
    resource: "@EdukodasFixturesBundle/Resources/config/routing.yml"
    prefix:   /

edukodas_tasks:
    resource: "@EdukodasTasksBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
