fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

edukodas_user:
    resource: "@EdukodasUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller"
    type: annotation
