# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.example:
        class: AppBundle\Service\ExampleService
        arguments: ["@doctrine.orm.entity_manager"]
    gedmo.listener.softdeleteable:
            class: Gedmo\SoftDeleteable\SoftDeleteableListener
            tags:
                - { name: doctrine.event_subscriber, connection: default }
            calls:
                - [ setAnnotationReader, [ "@annotation_reader" ] ]