edukodas_search_student:
    path:     /student/{searchString}
    defaults: { _controller: EdukodasSearchBundle:Search:searchStudent }

edukodas_search_teacher:
    path:     /teacher/{searchString}
    defaults: { _controller: EdukodasSearchBundle:Search:searchTeacher }
