genn_test_name:
    path:      /name/{name}
    defaults:  { _controller: GennTestBundle:Some:name, name: 'anonimous' }

genn_test_number:
    path:      /number/{max}
    defaults:  { _controller: GennTestBundle:Some:number, max: 1 }