edukodas_user_list:
  path:     /list_users
  defaults: { _controller: EdukodasUserBundle:UserList:index }

edukodas_user_list_update:
  path:     /list_users/update
  defaults: { _controller: EdukodasUserBundle:UserList:list, teamId: null, classId: null }
