edukodas_user_list:
  path:     /list_users
  defaults: { _controller: EdukodasUserBundle:UserList:list }

edukodas_remove_picture:
  path:     /picture/remove
  defaults: { _controller: EdukodasUserBundle:Profile:removePicture }
