edukodas_teacher_profile:
    path:     /
    defaults: { _controller: EdukodasProfileBundle:TeacherProfile:index }

student_profile:
  path: /profile/{id}
  defaults: { _controller: EdukodasProfileBundle:StudentProfile:index, id: null }

edit_student_profile:
  path: /profile/edit/
  defaults: { _controller: EdukodasProfileBundle:StudentProfile:edit }
