services:
  edukodas.profile_pic.twig.extension:
    class: Edukodas\Bundle\TemplateBundle\Twig\ProfilePictureExtension
    arguments: ['%profile_pic_web_dir%']
    public: false
    tags:
      - {name: twig.extension}
