services:
  edukodas.pointhistory.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Edukodas\Bundle\StatisticsBundle\Entity\PointHistory
    calls:
      - [setPageSize, ['%user_list_page_size%']]
      - [setPaginator, ['@knp_paginator']]

  edukodas.graph:
    class: Edukodas\Bundle\StatisticsBundle\Service\GraphService
    arguments:
      - '@edukodas.pointhistory.repository'
