services:
  edukodas.pointhistory.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Edukodas\Bundle\StatisticsBundle\Entity\PointHistory

  edukodas.statistics:
    class: Edukodas\Bundle\StatisticsBundle\Service\StatisticsService
    arguments:
      - '@edukodas.pointhistory.repository'
